compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project
build:
  image: python:3.5.1
  commands:
    - pip install -r requirements.txt
    - python manage.py migrate
    - python -Wall manage.py test
  environment:
    - DATABASE_URL=postgres://postgres:postgres@localhost:5432/project
    - DJANGO_SETTINGS_MODULE=project.settings.test
    - SECRET_KEY=changeme
